import GlossaryPage from "@/components/glossary/GlossaryPage";

const CustomerNarrative = () => (
  <GlossaryPage
    slug="customer-narrative"
    term="Customer Narrative"
    title="Customer Narrative"
    metaDescription="A Customer Narrative is an AI-generated, cited strategic document explaining the why behind a B2B SaaS customer relationship. Definition and examples."
    shortDefinition="A Customer Narrative is an AI-generated, continuously updated strategic document that explains the why behind a B2B SaaS customer relationship."
    updated="2026-06-01"
    body={
      <>
        <p>
          A Customer Narrative is the core artifact produced by a Customer
          Context Platform. It is a living, structured document — typically
          organized into sections like Why they bought, What success looks
          like, Who the champion is, Risk signals, and Renewal posture — that
          assembles understanding from the data sources around an account
          (calls, emails, tickets, CRM).
        </p>
        <p>
          Two properties make a Customer Narrative different from a CRM record
          or a CSM's headcanon. First, every claim is cited to the source it
          came from — a specific Gong call with timestamp, an email thread, a
          ticket — so the team can verify rather than trust. Second, it updates
          continuously as new context arrives, so the picture does not go stale
          between QBRs.
        </p>
      </>
    }
    whyItMatters={
      <>
        <p>
          The single most painful failure mode in Customer Success is the
          moment a customer realizes their CSM does not understand them. It
          happens at handovers, after reorgs, and in week three of onboarding
          when the customer is asked to walk through their goals again. Every
          time it happens, trust takes a hit and the renewal gets quietly
          harder.
        </p>
        <p>
          A Customer Narrative makes the understanding portable. The CSM reads
          instead of asks. The new rep ramps in days instead of months. The
          customer feels like the company actually remembers them — because it
          does.
        </p>
      </>
    }
    relatedTerms={[
      {
        label: "Customer Context Platform",
        to: "/glossary/customer-context-platform",
        description: "The category of software that produces Customer Narratives.",
      },
      {
        label: "Account Narrative",
        to: "/glossary/account-narrative",
        description: "Synonymous with Customer Narrative, scoped to a single account.",
      },
      {
        label: "AI Success Plans",
        to: "/glossary/ai-success-plans",
        description: "Plans Cohvia auto-generates from the Customer Narrative.",
      },
    ]}
    faqs={[
      {
        question: "Who writes the Customer Narrative?",
        answer:
          "The first draft is AI-generated by Cohvia from the data sources connected to the account — call recordings, email, tickets, CRM. The CSM (and at the sales-to-CS handover, the AE) reviews and enriches it with the parts the AI cannot see: verbal commitments, internal politics, and the real reason a champion fought for the deal. The narrative is owned by the team, not by the AI.",
      },
      {
        question: "How is a Customer Narrative different from a CRM account record?",
        answer:
          "A CRM record is a structured list of fields — ARR, stage, renewal date, owner. It tells you what and when. A Customer Narrative is a strategic document that tells you why: why they bought, what success means to them, who matters in the room, what is quietly going wrong. It complements the CRM rather than replacing it.",
      },
      {
        question: "Is the Customer Narrative shared with the customer?",
        answer:
          "By default, no. The Customer Narrative is an internal artifact for the CS team. Customer-facing plans, goals, and progress are shared separately through Cohvia's branded customer portal, where the CSM curates exactly what the customer sees on a per-milestone basis.",
      },
    ]}
  />
);

export default CustomerNarrative;
